### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by stochasticForest** [joshuaeckroth/clj-ml#10]
I'm using Debian Jessie.

I get the following error:

REPL-y 0.3.7, nREPL 0.2.10
Clojure 1.7.0
OpenJDK 64-Bit Server VM 1.7.0_91-b02
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

weka-ml.core=>  (use 'clj-ml.classifiers 'clj-ml.data 'clj-ml.utils)

CompilerException java.lang.UnsupportedClassVersionError: cljml/ClojureStreamFilter : Unsupported major.minor version 52.0, compiling:(clj_ml/filters.clj:1:1) 
weka-ml.core=> 

What might I be missing ?

**Comment by joshuaeckroth** [comment]
cljml/ClojureStreamFilter is a class in this project's src/java folder. It is precompiled in the Clojar. You can probably fix this problem by downloading this project's source and running lein install. That will cause it to recompile using your version of Java, and install it to your ~/.m2 folder.

I'll look into distributing a better Jar that is more compatible with older versions of Java.

Alternatively, you could upgrade your JDK to Java 8.

**Comment by stochasticForest** [comment]
Thank you for your timely and clear identification of the problem Joshua.

I've update my JDK from the default version 7 of Debian Jessie to JDK 8.


That seems to have resolved the issue,

many thanks :)

**Comment by stochasticForest** [comment]
Thank you for your timely and clear identification of the problem Joshua.

I've update my JDK from the default version 7 of Debian Jessie to JDK 8.


That seems to have resolved the issue,

many thanks :)

**Comment by stochasticForest** [comment]
Thank you for your timely and clear identification of the problem Joshua.

I've update my JDK from the default version 7 of Debian Jessie to JDK 8.


That seems to have resolved the issue,

many thanks :)
