### ISSUE TITLE
java 1.7 compatibility

### ISSUE THREAD

**Issue by lisp** [joshuaeckroth/clj-ml#8]
the readme suggests 1.7 compatibility, but an attempt to use the jar which is obtained from [cc.artifice/clj-ml "0.6.0"] leads to

    java.lang.UnsupportedClassVersionError: cljml/ClojureStreamFilter : Unsupported major.minor version 52.0

if a cloned clj-ml is built on the local system, that is with the 1.7 runtime and installed in the local repository, the error does not occur.

is there some process to make the 1.7 version available for use without a local build?

**Comment by joshuaeckroth** [comment]
Ok, I deployed 0.6.1 which should work on Java 1.7. Please let me know if it does not.



On October 13, 2015 at 6:20:37 AM, james anderson (notifications@github.com<mailto:notifications@github.com>) wrote:

the readme suggests 1.7 compatibility, but an attempt to use the jar which is obtained from [cc.artifice/clj-ml "0.6.0"] leads to

java.lang.UnsupportedClassVersionError: cljml/ClojureStreamFilter : Unsupported major.minor version 52.0



if a cloned clj-ml is built on the local system, that is with the 1.7 runtime and installed in the local repository. the error does not occur.

is there some process to make the 1.7 version available for use without a local build?

**Comment by lisp** [comment]
yes, the 0.6.1 resolved this.
